#!/bin/bash

# ・ 目的
# 開発時にブラウザへのアクセスを簡単にする。
# 引数でコントローラ名やアクション名を指定しfirefoxを開く。
# 調べごとにはChromeを使用しているため、Chromeを完全に閉じることは難しい。
# そのため頻繁に完全に閉じることができるのはfirefoxを使用する。（コマンドラインから使いやすいというメリットもある）

# ・ 使い方
# ./open_firefox controller_name action_name id
# 上記のように入力して実行すると。
# http://172.17.0.2:3000/controller_name/action_name/id のURLを生成しfirefoxを開く。
# 必要に応じて末尾に&をつけてバックグラウンドで再生すると便利に使えるかもしれない。
# 先頭の ./ の入力が面倒であれば~/.bash_aliases にエイリアスを登録すると短くできる。

#IPアドレスとポートを元に接続先を記述する
URL="172.17.0.2:3000"
#アクセスする先をコマンドの引数から取得し上書き
for i in $@
do
    URL=$URL"/"$i
done

#現在の設定ではSSL/TLSは有効にしていないため以下のURLとして上書き
URL="http://"$URL

#firefoxで接続する。
#ターミナル上に現れる文字は今回不要なのでリダイレクト先を変更する。
firefox $URL > /dev/null 2>&1