development:
  adapter: redis
  url: redis://172.19.0.3:6379

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails_dir_production
