' ログイン画面の画面遷移について記述する。
@startuml iteration_1_view_transition
    title イテレーション1における画面遷移
    hide empty description
    
    ' ログインとログアウトの画面
    ' はじめにアクセスすると認証画面が表示される。
    [*]--> 選択画面 : ページにアクセス
    
    選択画面 --> 基本認証画面 : アカウントを持っているとき
    選択画面 -->ログイン情報登録画面 : アカウントを持っていない

    基本認証画面-->マイページ : ログイン成功
    基本認証画面 --> [*]: ログイン失敗

    ログイン情報登録画面 -->マイページ : 登録情報でログイン

    マイページ -> ログアウトページ : ログアウトする
    ログアウトページ --> 選択画面 : 元にもどる
    
    ' 何もなければ終了
    [*]  <- 選択画面 : 操作が終了すれば完了

    'チャット機能の画面まで移動
    マイページ --> ルーム一覧
    ルーム一覧 --> マイページ
    ルーム一覧 -> ルーム
    ルーム     -> ルーム一覧 
@enduml