' ログイン画面の画面遷移について記述する。
@startuml login_view_transition
    title ログインに関する画面遷移について
    hide empty description
    
    ' はじめにアクセスすると認証画面が表示される。
    [*]-->ログイン画面 : ページにアクセス

    ログイン画面->ログイン失敗画面 : ログイン失敗
    ログイン画面-->ログイン情報登録画面 : アカウントを持っていない
    ログイン画面-->ログイン成功画面 : ログイン成功

    ログイン失敗画面 -> ログイン失敗画面 : 再ログイン失敗
    ログイン失敗画面 -->ログイン情報登録画面
    ログイン失敗画面 --> ログイン成功画面 : ログイン成功

    ログイン情報登録画面 -->ログイン成功画面 : 登録情報でログイン

    ログイン成功画面 -->ログイン画面 : ログアウトすると元に戻る
    
    ' 何もなければ終了
    [*]<-ログイン画面 : 操作が終了すれば完了
@enduml